package main.protocol;

public enum ProtocolCommand
{
    REQUEST_EXCHANGE_SERVER_PUBLIC_KEY_AND_SEND_IV(),
    REQUEST_EXCHANGE_SERVER_PUBLIC_KEY_OK(),
    REQUEST_EXCHANGE_SERVER_PUBLIC_KEY_KO(),
    SIGN_UP(),
    SIGN_UP_OK(),
    SIGN_UP_KO(),
    SIGN_IN(),
    SIGN_IN_OK(),
    SIGN_IN_KO(),
    SIGN_OUT(),
    SIGN_OUT_OK(),
    SIGN_OUT_KO(),
    CREATE_ANNONCE(),
    CREATE_ANNONCE_OK(),
    CREATE_ANNONCE_KO(),
    UPDATE_ANNONCE(),
    UPDATE_ANNONCE_OK(),
    UPDATE_ANNONCE_KO(),
    DOMAINS_LIST(),
    DOMAINS_LIST_OK(),
    DOMAINS_LIST_KO(),
    ANNONCE_FROM_DOMAIN(),
    ANNONCE_FROM_DOMAIN_OK(),
    ANNONCE_FROM_DOMAIN_KO(),
    REMOVE_ANNONCE(),
    REMOVE_ANNONCE_OK(),
    REMOVE_ANNONCE_KO()
}